name: PHPStan

on:
  push: null

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-main"

jobs:
  phpstan:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: 'Rector 0.12'
            run: vendor/bin/phpstan analyse --ansi --debug -vvv
          - name: 'Rector 0.13'
            run: |
              composer require rector/rector ^0.13
              vendor/bin/phpstan analyse --ansi --debug -vvv
          - name: 'Rector 0.13 and PHPStan 1.6'
            run: |
              composer require rector/rector ^0.13
              composer require phpstan/phpstan "1.6.*"
              vendor/bin/phpstan analyse --ansi --debug -vvv

    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - uses: "ramsey/composer-install@v1"
      - run: ${{ matrix.actions.run }}
